Added chat
Joeyh021/SoftEng-Project pull request #67
Opened 2022-03-03 09:46 UTC by piotrszelejewski

Yeah, chat

2022-03-03 12:21 UTC, joshdavies14 requested changes
I think this all LGTM besides my two comments! :)

2022-03-03 12:21 UTC, joshdavies14 commented on people/templates/people/chat.html
> +  <input type="submit" value="Send" />
```suggestion
  <input class="btn btn-primary" type="submit" value="Send" />
```

2022-03-03 12:21 UTC, joshdavies14 commented on people/templates/people/chat.html
> +    <p style="text-align:left;background-color:rgb(127, 108, 238);">{{ chatMessage.content }}</p>
We probably want to change the colours, or remove them entirely - they aren't the most readable and I imagine wouldn't pass accessibility contrast checks in their current state

2022-03-04 08:49 UTC, piotrszelejewski commented on people/templates/people/chat.html
> +    <p style="text-align:left;background-color:rgb(127, 108, 238);">{{ chatMessage.content }}</p>
I agree

2022-03-04 16:35 UTC, joshdavies14 approved these changes
Sorry. it's been a day. LGTM! :)

2022-03-05 17:52 UTC, merged